window.__justep.__ResourceEngine.loadCss([{url: '/system/components/comp.min.css', include: '$model/system/components/justep/row/css/row,$model/system/components/justep/attachment/css/attachment,$model/system/components/justep/barcode/css/barcodeImage,$model/system/components/bootstrap/form/css/form,$model/system/components/justep/panel/css/panel,$model/system/components/bootstrap/accordion/css/accordion,$model/system/components/justep/common/css/scrollable,$model/system/components/bootstrap/pager/css/pager,$model/system/components/justep/scrollView/css/scrollView,$model/system/components/justep/input/css/datePickerPC,$model/system/components/bootstrap/navs/css/navs,$model/system/components/justep/contents/css/contents,$model/system/components/justep/popMenu/css/popMenu,$model/system/components/justep/lib/css/icons,$model/system/components/justep/titleBar/css/titleBar,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/justep/dialog/css/dialog,$model/system/components/justep/messageDialog/css/messageDialog,$model/system/components/bootstrap/navbar/css/navbar,$model/system/components/justep/toolBar/css/toolBar,$model/system/components/justep/popOver/css/popOver,$model/system/components/justep/loadingBar/loadingBar,$model/system/components/justep/input/css/datePicker,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/bootstrap/dialog/css/dialog,$model/system/components/justep/wing/css/wing,$model/system/components/bootstrap/scrollSpy/css/scrollSpy,$model/system/components/justep/menu/css/menu,$model/system/components/justep/numberSelect/css/numberList,$model/system/components/justep/list/css/list,$model/system/components/bootstrap/carousel/css/carousel,$model/system/components/bootstrap/dropdown/css/dropdown,$model/system/components/justep/common/css/forms,$model/system/components/justep/bar/css/bar,$model/system/components/bootstrap/tabs/css/tabs,$model/system/components/bootstrap/pagination/css/pagination'},{url: '/system/components/bootstrap.min.css', include: '$model/system/components/bootstrap/lib/css/bootstrap,$model/system/components/bootstrap/lib/css/bootstrap-theme'}]);window.__justep.__ResourceEngine.loadJs(['/system/components/comp.min.js','/system/common.min.js','/system/core.min.js']);define(function(require){
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/labelEdit/labelEdit');
require('$model/UI2/system/components/justep/row/row');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/button/buttonGroup');
require('$model/UI2/system/components/justep/list/list');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/contents/contents');
require('$model/UI2/system/components/justep/scrollView/scrollView');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/contents/content');
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/output/output');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/costacoSecond/searchPage/MtoMSearch/forecastDetails'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='__baseID__';
	this.__cid='cQjIvq2';
	this._flag_='17f09cdfec8a149b23b2a3006b779ca9';
	this.callParent(contextUrl);
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"applyname":{"define":"applyname","label":"委托单位：","name":"applyname","relation":"applyname","type":"String"},"cargoname":{"define":"cargoname","label":"货物名称：","name":"cargoname","relation":"cargoname","type":"String"},"consignee":{"define":"consignee","label":"收货人：","name":"consignee","relation":"consignee","type":"String"},"contact":{"define":"contact","label":"联系方式：","name":"contact","relation":"contact","type":"String"},"contactuser":{"define":"contactuser","label":"联系人：","name":"contactuser","relation":"contactuser","type":"String"},"customer_shortcall":{"define":"customer_shortcall","label":"委托单位（简称）","name":"customer_shortcall","relation":"customer_shortcall","type":"String"},"mark":{"define":"mark","label":"标　　志：","name":"mark","relation":"mark","type":"String"},"note":{"define":"note","label":"备　　注：","name":"note","relation":"note","type":"String"},"numbersofpackages":{"define":"numbersofpackages","label":"件　　数：","name":"numbersofpackages","relation":"numbersofpackages","type":"String"},"operating_type_zh":{"define":"operating_type_zh","label":"拆箱方式：","name":"operating_type_zh","relation":"operating_type_zh","type":"String"},"orderdate":{"define":"orderdate","label":"委托时间：","name":"orderdate","relation":"orderdate","type":"String"},"orderid":{"define":"orderid","label":"委托编号：","name":"orderid","relation":"orderid","type":"String"},"package":{"define":"package","label":"包　　装：","name":"package","relation":"package","type":"String"},"unpackagingplace":{"define":"unpackagingplace","label":"拆箱地点：","name":"unpackagingplace","relation":"unpackagingplace","type":"String"},"voyage":{"define":"voyage","label":"航　　次：","name":"voyage","relation":"voyage","type":"String"},"vslname":{"define":"vslname","label":"船舶名称：","name":"vslname","relation":"vslname","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"forecastdetailsCustomRefresh"},"idColumn":"orderid","limit":20,"xid":"forecastdetails"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"ctnno":{"define":"ctnno","label":"箱号","name":"ctnno","relation":"ctnno","type":"String"},"ctnsize":{"define":"ctnsize","label":"箱尺寸","name":"ctnsize","relation":"ctnsize","type":"String"},"ctntype":{"define":"ctntype","label":"箱型","name":"ctntype","relation":"ctntype","type":"String"},"flflag":{"define":"flflag","label":"整拼标志","name":"flflag","relation":"flflag","type":"String"},"flflag_zh":{"define":"flflag_zh","name":"flflag_zh","relation":"flflag_zh","type":"String"},"numbersofpackages":{"define":"numbersofpackages","label":"件数","name":"numbersofpackages","relation":"numbersofpackages","type":"String"},"sealno":{"define":"sealno","label":"铅封号","name":"sealno","relation":"sealno","type":"String"},"volume":{"define":"volume","label":"体积","name":"volume","relation":"volume","type":"String"}},"directDelete":false,"events":{},"idColumn":"ctnno","limit":20,"xid":"boxlist"});
}}); 
return __result;});
