window.__justep.__ResourceEngine.loadCss([{url: '/system/components/comp.min.css', include: '$model/system/components/justep/row/css/row,$model/system/components/justep/attachment/css/attachment,$model/system/components/justep/barcode/css/barcodeImage,$model/system/components/bootstrap/form/css/form,$model/system/components/justep/panel/css/panel,$model/system/components/bootstrap/accordion/css/accordion,$model/system/components/justep/common/css/scrollable,$model/system/components/bootstrap/pager/css/pager,$model/system/components/justep/scrollView/css/scrollView,$model/system/components/justep/input/css/datePickerPC,$model/system/components/bootstrap/navs/css/navs,$model/system/components/justep/contents/css/contents,$model/system/components/justep/popMenu/css/popMenu,$model/system/components/justep/lib/css/icons,$model/system/components/justep/titleBar/css/titleBar,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/justep/dialog/css/dialog,$model/system/components/justep/messageDialog/css/messageDialog,$model/system/components/bootstrap/navbar/css/navbar,$model/system/components/justep/toolBar/css/toolBar,$model/system/components/justep/popOver/css/popOver,$model/system/components/justep/loadingBar/loadingBar,$model/system/components/justep/input/css/datePicker,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/bootstrap/dialog/css/dialog,$model/system/components/justep/wing/css/wing,$model/system/components/bootstrap/scrollSpy/css/scrollSpy,$model/system/components/justep/menu/css/menu,$model/system/components/justep/numberSelect/css/numberList,$model/system/components/justep/list/css/list,$model/system/components/bootstrap/carousel/css/carousel,$model/system/components/bootstrap/dropdown/css/dropdown,$model/system/components/justep/common/css/forms,$model/system/components/justep/bar/css/bar,$model/system/components/bootstrap/tabs/css/tabs,$model/system/components/bootstrap/pagination/css/pagination'},{url: '/system/components/bootstrap.min.css', include: '$model/system/components/bootstrap/lib/css/bootstrap,$model/system/components/bootstrap/lib/css/bootstrap-theme'}]);window.__justep.__ResourceEngine.loadJs(['/system/components/comp.min.js','/system/common.min.js','/system/core.min.js']);define(function(require){
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/labelEdit/labelEdit');
require('$model/UI2/system/components/justep/row/row');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/list/list');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/contents/contents');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/scrollView/scrollView');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/select/select');
require('$model/UI2/system/components/justep/contents/content');
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/input/input');
require('$model/UI2/system/components/justep/output/output');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/costacoSecond/searchPage/MtoMSearch/plansearch'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='__baseID__';
	this.__cid='cmEbuI3';
	this._flag_='309612c4a9ca50bf9f28af0cd0c6b20d';
	this.callParent(contextUrl);
 require('css!$UI/costaco/ajax/jquery-ui.min').load();
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"id":{"define":"id","name":"id","relation":"id","type":"String"},"ship_name":{"define":"ship_name","label":"船名","name":"ship_name","relation":"ship_name","type":"String"},"shipcode":{"define":"shipcode","label":"船值","name":"shipcode","relation":"shipcode","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"shipInfoCustomRefresh"},"idColumn":"shipcode","limit":20,"xid":"shipInfo"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"customer_name":{"define":"customer_name","label":"委托方名","name":"customer_name","relation":"customer_name","type":"String"},"id":{"define":"id","label":"委托方值","name":"id","relation":"id","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"customerInfoCustomRefresh"},"idColumn":"id","limit":20,"xid":"customerInfo"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"id":{"define":"id","name":"id","relation":"id","type":"String"},"location_name":{"define":"location_name","label":"场地名","name":"location_name","relation":"location_name","type":"String"},"locationcode":{"define":"locationcode","label":"场地值","name":"locationcode","relation":"locationcode","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"locationDataCustomRefresh"},"idColumn":"locationcode","limit":20,"xid":"locationData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"entrustdept":{"define":"entrustdept","label":"委托方","name":"entrustdept","relation":"entrustdept","type":"String"},"entrusttime":{"define":"entrusttime","label":"委托时间","name":"entrusttime","relation":"entrusttime","rules":{"date":true},"type":"Date"},"locationno":{"define":"locationno","label":"作业场地","name":"locationno","relation":"locationno","type":"String"},"shipname":{"define":"shipname","label":"船名","name":"shipname","relation":"shipname","type":"String"},"voyage":{"define":"voyage","label":"航次","name":"voyage","relation":"voyage","type":"String"}},"directDelete":false,"events":{},"idColumn":"entrusttime","initData":"[{}]","limit":20,"xid":"entrusttimeData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"id":{"define":"id","name":"id","relation":"id","type":"String"},"sys":{"define":"sys","label":"系统名称","name":"sys","relation":"sys","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","initData":"[{\"id\":\"cfs\",\"sys\":\"cfs\"},{\"id\":\"qbzx\",\"sys\":\"起驳装箱\"},{\"id\":\"chaixiang\",\"sys\":\"chaixiang\"}]","limit":20,"xid":"system"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"applyname":{"define":"applyname","label":"委托单位：","name":"applyname","relation":"applyname","type":"String"},"blno":{"define":"blno","label":"提单号：","name":"blno","relation":"blno","type":"String"},"customer_shortname":{"define":"customer_shortname","label":"委托单位（简称）","name":"customer_shortname","relation":"customer_shortname","type":"String"},"id":{"define":"id","label":"ID","name":"id","relation":"id","type":"String"},"orderdate":{"define":"orderdate","label":"委托日期：","name":"orderdate","relation":"orderdate","type":"String"},"orderid":{"define":"orderid","label":"委托编号：","name":"orderid","relation":"orderid","type":"String"},"unpackagingplace":{"define":"unpackagingplace","label":"拆箱地点：","name":"unpackagingplace","relation":"unpackagingplace","type":"String"},"voyage":{"define":"voyage","label":"航　　次：","name":"voyage","relation":"voyage","type":"String"},"vslname":{"define":"vslname","label":"船　　名：","name":"vslname","relation":"vslname","type":"String"}},"directDelete":false,"events":{},"idColumn":"orderid","limit":20,"xid":"planDetailsData"});
 var justep = require('$UI/system/lib/justep');if(!this['__justep__']) this['__justep__'] = {};if(!this['__justep__'].selectOptionsAfterRender)	this['__justep__'].selectOptionsAfterRender = function($element) {		var comp = justep.Component.getComponent($element);		if(comp) comp._addDefaultOption();	};if(!this['__justep__'].selectOptionsBeforeRender)	this['__justep__'].selectOptionsBeforeRender = function($element) {		var comp = justep.Component.getComponent($element);		if(comp) comp._optionsBeforeRender();	};
 var justep = require('$UI/system/lib/justep');if(!this['__justep__']) this['__justep__'] = {};if(!this['__justep__'].selectOptionsAfterRender)	this['__justep__'].selectOptionsAfterRender = function($element) {		var comp = justep.Component.getComponent($element);		if(comp) comp._addDefaultOption();	};if(!this['__justep__'].selectOptionsBeforeRender)	this['__justep__'].selectOptionsBeforeRender = function($element) {		var comp = justep.Component.getComponent($element);		if(comp) comp._optionsBeforeRender();	};
}}); 
return __result;});
