window.__justep.__ResourceEngine.loadCss([{url: '/system/components/comp.min.css', include: '$model/system/components/justep/row/css/row,$model/system/components/justep/attachment/css/attachment,$model/system/components/justep/barcode/css/barcodeImage,$model/system/components/bootstrap/form/css/form,$model/system/components/justep/panel/css/panel,$model/system/components/bootstrap/accordion/css/accordion,$model/system/components/justep/common/css/scrollable,$model/system/components/bootstrap/pager/css/pager,$model/system/components/justep/scrollView/css/scrollView,$model/system/components/justep/input/css/datePickerPC,$model/system/components/bootstrap/navs/css/navs,$model/system/components/justep/contents/css/contents,$model/system/components/justep/popMenu/css/popMenu,$model/system/components/justep/lib/css/icons,$model/system/components/justep/titleBar/css/titleBar,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/justep/dialog/css/dialog,$model/system/components/justep/messageDialog/css/messageDialog,$model/system/components/bootstrap/navbar/css/navbar,$model/system/components/justep/toolBar/css/toolBar,$model/system/components/justep/popOver/css/popOver,$model/system/components/justep/loadingBar/loadingBar,$model/system/components/justep/input/css/datePicker,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/bootstrap/dialog/css/dialog,$model/system/components/justep/wing/css/wing,$model/system/components/bootstrap/scrollSpy/css/scrollSpy,$model/system/components/justep/menu/css/menu,$model/system/components/justep/numberSelect/css/numberList,$model/system/components/justep/list/css/list,$model/system/components/bootstrap/carousel/css/carousel,$model/system/components/bootstrap/dropdown/css/dropdown,$model/system/components/justep/common/css/forms,$model/system/components/justep/bar/css/bar,$model/system/components/bootstrap/tabs/css/tabs,$model/system/components/bootstrap/pagination/css/pagination'},{url: '/system/components/bootstrap.min.css', include: '$model/system/components/bootstrap/lib/css/bootstrap,$model/system/components/bootstrap/lib/css/bootstrap-theme'}]);window.__justep.__ResourceEngine.loadJs(['/system/components/comp.min.js','/system/common.min.js','/system/core.min.js']);define(function(require){
require('$model/UI2/system/components/justep/labelEdit/labelEdit');
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/row/row');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/contents/content');
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/contents/contents');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/output/output');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/costacoSecond/searchPage/cfsSearch/danzhengDetails'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='__baseID__';
	this.__cid='cZfQNje';
	this._flag_='2692d8c731f8cad310555b23112ef230';
	this.callParent(contextUrl);
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"cargo_weight":{"define":"cargo_weight","label":"货物重量：","name":"cargo_weight","relation":"cargo_weight","type":"String"},"consignee":{"define":"consignee","label":"收货人：","name":"consignee","relation":"consignee","type":"String"},"ctn_no":{"define":"ctn_no","label":"箱号：","name":"ctn_no","relation":"ctn_no","type":"String"},"cube":{"define":"cube","label":"箱型尺寸：","name":"cube","relation":"cube","type":"String"},"damaged_quantity":{"define":"damaged_quantity","label":"总残损数：","name":"damaged_quantity","relation":"damaged_quantity","type":"String"},"danger_rank":{"define":"danger_rank","label":"危险等级：","name":"danger_rank","relation":"danger_rank","type":"String"},"empty_weight":{"define":"empty_weight","label":"空箱重量：","name":"empty_weight","relation":"empty_weight","type":"String"},"fl":{"define":"fl","label":"整拼标志：","name":"fl","relation":"fl","rules":{"integer":true},"type":"Integer"},"remark":{"define":"remark","label":"备注：","name":"remark","relation":"remark","type":"String"},"seal_no":{"define":"seal_no","label":"铅封号：","name":"seal_no","relation":"seal_no","type":"String"},"shipname":{"define":"shipname","label":"船名：","name":"shipname","relation":"shipname","type":"String"},"sling":{"define":"sling","label":"关数：","name":"sling","relation":"sling","type":"String"},"units":{"define":"units","label":"总件数：","name":"units","relation":"units","type":"String"},"vargo":{"define":"vargo","label":"航次：","name":"vargo","relation":"vargo","type":"String"},"votes":{"define":"votes","label":"总票数：","name":"votes","relation":"votes","type":"String"},"weights":{"define":"weights","label":"总重量：","name":"weights","relation":"weights","type":"String"},"zhoperator":{"define":"zhoperator","label":"理货员：","name":"zhoperator","relation":"zhoperator","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"danzhengCustomRefresh"},"idColumn":"ctn_no","limit":20,"xid":"danzheng"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"bl_no":{"define":"bl_no","label":"提单号：","name":"bl_no","relation":"bl_no","type":"String"},"cargo_unit":{"define":"cargo_unit","label":"货物件数：","name":"cargo_unit","relation":"cargo_unit","type":"String"},"damage_unit":{"define":"damage_unit","label":"残损数：","name":"damage_unit","relation":"damage_unit","type":"String"},"mark":{"define":"mark","label":"标　　志：","name":"mark","relation":"mark","type":"String"},"package":{"define":"package","label":"包　　装：","name":"package","relation":"package","type":"String"}},"directDelete":false,"events":{},"idColumn":"bl_no","limit":20,"xid":"tidanhao"});
}}); 
return __result;});
