window.__justep.__ResourceEngine.loadCss([{url: '/system/components/comp.min.css', include: '$model/system/components/justep/row/css/row,$model/system/components/justep/attachment/css/attachment,$model/system/components/justep/barcode/css/barcodeImage,$model/system/components/bootstrap/form/css/form,$model/system/components/justep/panel/css/panel,$model/system/components/bootstrap/accordion/css/accordion,$model/system/components/justep/common/css/scrollable,$model/system/components/bootstrap/pager/css/pager,$model/system/components/justep/scrollView/css/scrollView,$model/system/components/justep/input/css/datePickerPC,$model/system/components/bootstrap/navs/css/navs,$model/system/components/justep/contents/css/contents,$model/system/components/justep/popMenu/css/popMenu,$model/system/components/justep/lib/css/icons,$model/system/components/justep/titleBar/css/titleBar,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/justep/dialog/css/dialog,$model/system/components/justep/messageDialog/css/messageDialog,$model/system/components/bootstrap/navbar/css/navbar,$model/system/components/justep/toolBar/css/toolBar,$model/system/components/justep/popOver/css/popOver,$model/system/components/justep/loadingBar/loadingBar,$model/system/components/justep/input/css/datePicker,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/bootstrap/dialog/css/dialog,$model/system/components/justep/wing/css/wing,$model/system/components/bootstrap/scrollSpy/css/scrollSpy,$model/system/components/justep/menu/css/menu,$model/system/components/justep/numberSelect/css/numberList,$model/system/components/justep/list/css/list,$model/system/components/bootstrap/carousel/css/carousel,$model/system/components/bootstrap/dropdown/css/dropdown,$model/system/components/justep/common/css/forms,$model/system/components/justep/bar/css/bar,$model/system/components/bootstrap/tabs/css/tabs,$model/system/components/bootstrap/pagination/css/pagination'},{url: '/system/components/bootstrap.min.css', include: '$model/system/components/bootstrap/lib/css/bootstrap,$model/system/components/bootstrap/lib/css/bootstrap-theme'}]);window.__justep.__ResourceEngine.loadJs(['/system/components/comp.min.js','/system/common.min.js','/system/core.min.js']);define(function(require){
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/labelEdit/labelEdit');
require('$model/UI2/system/components/justep/row/row');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/button/buttonGroup');
require('$model/UI2/system/components/justep/list/list');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/contents/contents');
require('$model/UI2/system/components/justep/scrollView/scrollView');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/contents/content');
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/output/output');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/costacoSecond/searchPage/qbzxSearch/forecastDetails'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='__baseID__';
	this.__cid='cfEVvIj';
	this._flag_='7b3622b62acec90fee44f662e85631a4';
	this.callParent(contextUrl);
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"customer":{"define":"customer","label":"委托单位：","name":"customer","relation":"customer","type":"String"},"entrust_time":{"define":"entrust_time","label":"委托时间：","name":"entrust_time","relation":"entrust_time","type":"String"},"entrustno":{"define":"entrustno","label":"委托编号：","name":"entrustno","relation":"entrustno","type":"String"},"id":{"define":"id","label":"预报编号：","name":"id","relation":"id","type":"String"},"location_name":{"define":"location_name","label":"理货地点：","name":"location_name","relation":"location_name","type":"String"},"packing_require":{"define":"packing_require","label":"装箱要求：","name":"packing_require","relation":"packing_require","type":"String"},"ship_name":{"define":"ship_name","label":"船舶名称：","name":"ship_name","relation":"ship_name","type":"String"},"total_ctn":{"define":"total_ctn","label":"总 箱 数：","name":"total_ctn","relation":"total_ctn","type":"String"},"total_package":{"define":"total_package","label":"总 件 数：","name":"total_package","relation":"total_package","type":"String"},"total_ticket":{"define":"total_ticket","label":"总 票 数：","name":"total_ticket","relation":"total_ticket","type":"String"},"total_weight":{"define":"total_weight","label":"总 重 量：","name":"total_weight","relation":"total_weight","type":"String"},"voyage":{"define":"voyage","label":"航　　次：","name":"voyage","relation":"voyage","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"forecastdetailsCustomRefresh"},"idColumn":"id","limit":20,"xid":"forecastdetails"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"billno":{"define":"billno","name":"billno","relation":"billno","type":"String"},"cargo_name":{"define":"cargo_name","name":"cargo_name","relation":"cargo_name","type":"String"},"dangerlevel":{"define":"dangerlevel","name":"dangerlevel","relation":"dangerlevel","type":"String"},"id":{"define":"id","name":"id","relation":"id","type":"String"},"mark":{"define":"mark","name":"mark","relation":"mark","type":"String"},"number":{"define":"number","name":"number","relation":"number","type":"String"},"pack":{"define":"pack","name":"pack","relation":"pack","type":"String"},"plan_id":{"define":"plan_id","name":"plan_id","relation":"plan_id","type":"String"},"total_weight":{"define":"total_weight","name":"total_weight","relation":"total_weight","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","limit":20,"xid":"goodlist"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"ctn_master":{"define":"ctn_master","name":"ctn_master","relation":"ctn_master","type":"String"},"ctn_type_code":{"define":"ctn_type_code","name":"ctn_type_code","relation":"ctn_type_code","type":"String"},"flflag_zh":{"define":"flflag_zh","name":"flflag_zh","relation":"flflag_zh","type":"String"},"id":{"define":"id","name":"id","relation":"id","type":"String"},"plan_id":{"define":"plan_id","name":"plan_id","relation":"plan_id","type":"String"},"quantity":{"define":"quantity","name":"quantity","relation":"quantity","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","limit":20,"xid":"boxlist"});
}}); 
return __result;});
