window.__justep.__ResourceEngine.loadCss([{url: '/system/components/comp.min.css', include: '$model/system/components/justep/row/css/row,$model/system/components/justep/attachment/css/attachment,$model/system/components/justep/barcode/css/barcodeImage,$model/system/components/bootstrap/form/css/form,$model/system/components/justep/panel/css/panel,$model/system/components/bootstrap/accordion/css/accordion,$model/system/components/justep/common/css/scrollable,$model/system/components/bootstrap/pager/css/pager,$model/system/components/justep/scrollView/css/scrollView,$model/system/components/justep/input/css/datePickerPC,$model/system/components/bootstrap/navs/css/navs,$model/system/components/justep/contents/css/contents,$model/system/components/justep/popMenu/css/popMenu,$model/system/components/justep/lib/css/icons,$model/system/components/justep/titleBar/css/titleBar,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/justep/dialog/css/dialog,$model/system/components/justep/messageDialog/css/messageDialog,$model/system/components/bootstrap/navbar/css/navbar,$model/system/components/justep/toolBar/css/toolBar,$model/system/components/justep/popOver/css/popOver,$model/system/components/justep/loadingBar/loadingBar,$model/system/components/justep/input/css/datePicker,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/bootstrap/dialog/css/dialog,$model/system/components/justep/wing/css/wing,$model/system/components/bootstrap/scrollSpy/css/scrollSpy,$model/system/components/justep/menu/css/menu,$model/system/components/justep/numberSelect/css/numberList,$model/system/components/justep/list/css/list,$model/system/components/bootstrap/carousel/css/carousel,$model/system/components/bootstrap/dropdown/css/dropdown,$model/system/components/justep/common/css/forms,$model/system/components/justep/bar/css/bar,$model/system/components/bootstrap/tabs/css/tabs,$model/system/components/bootstrap/pagination/css/pagination'},{url: '/system/components/bootstrap.min.css', include: '$model/system/components/bootstrap/lib/css/bootstrap,$model/system/components/bootstrap/lib/css/bootstrap-theme'}]);window.__justep.__ResourceEngine.loadJs(['/system/components/comp.min.js','/system/common.min.js','/system/core.min.js']);define(function(require){
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/labelEdit/labelEdit');
require('$model/UI2/system/components/justep/row/row');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/button/buttonGroup');
require('$model/UI2/system/components/justep/list/list');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/contents/contents');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/scrollView/scrollView');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/contents/content');
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/output/output');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/costacoSecond/searchPage/qbzxSearch/searchInstructionDetails'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='__baseID__';
	this.__cid='cMRj6ny';
	this._flag_='519b9538db98cabcf5ccfc36be3ef90b';
	this.callParent(contextUrl);
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":false,"autoNew":false,"confirmDelete":true,"confirmRefresh":true,"defCols":{"ctn_master":{"define":"ctn_master","label":"箱　　主：","name":"ctn_master","relation":"ctn_master","type":"String"},"ctn_type_code":{"define":"ctn_type_code","label":"箱型尺寸：","name":"ctn_type_code","relation":"ctn_type_code","type":"String"},"ctnno":{"define":"ctnno","label":"箱　　号：","name":"ctnno","relation":"ctnno","type":"String"},"id":{"define":"id","label":"箱id","name":"id","relation":"id","type":"String"},"instruction_id":{"define":"instruction_id","label":"指令id","name":"instruction_id","relation":"instruction_id","type":"String"},"status":{"define":"status","label":"状　　态：","name":"status","relation":"status","type":"String"},"status_zh":{"define":"status_zh","label":"状　　态：","name":"status_zh","relation":"status_zh","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","limit":20,"xid":"boxList"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"id":{"define":"id","label":"预报计划编号","name":"id","relation":"id","type":"String"},"location_name":{"define":"location_name","label":"理货地点：","name":"location_name","relation":"location_name","type":"String"},"packing_require":{"define":"packing_require","label":"装箱要求：","name":"packing_require","relation":"packing_require","type":"String"},"ship_name":{"define":"ship_name","label":"船　　名：","name":"ship_name","relation":"ship_name","type":"String"},"total_ctn":{"define":"total_ctn","label":"总 箱 数：","name":"total_ctn","relation":"total_ctn","type":"String"},"total_package":{"define":"total_package","label":"总 件 数：","name":"total_package","relation":"total_package","type":"String"},"total_ticket":{"define":"total_ticket","label":"总 票 数：","name":"total_ticket","relation":"total_ticket","type":"String"},"total_weight":{"define":"total_weight","label":"总 重 量：","name":"total_weight","relation":"total_weight","type":"String"},"voyage":{"define":"voyage","label":"航　　次：","name":"voyage","relation":"voyage","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","limit":20,"xid":"forecastPlanData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"containermaster":{"define":"containermaster","label":"箱主","name":"containermaster","relation":"containermaster","type":"String"},"containerno":{"define":"containerno","label":"箱号","name":"containerno","relation":"containerno","type":"String"},"containertypecode":{"define":"containertypecode","label":"箱型尺寸","name":"containertypecode","relation":"containertypecode","type":"String"},"insid":{"define":"insid","label":"指令id","name":"insid","relation":"insid","type":"String"}},"directDelete":false,"events":{},"idColumn":"insid","initData":"[{}]","limit":20,"xid":"boxdetails"});
 new __Data__(this,{"autoLoad":false,"autoNew":false,"confirmDelete":true,"confirmRefresh":true,"defCols":{"billno":{"define":"billno","label":"提单号：","name":"billno","relation":"billno","type":"String"},"cargo_name":{"define":"cargo_name","label":"货　名：","name":"cargo_name","relation":"cargo_name","type":"String"},"dangerlevel":{"define":"dangerlevel","label":"危险等级：","name":"dangerlevel","relation":"dangerlevel","type":"String"},"id":{"define":"id","label":"货物编号：","name":"id","relation":"id","type":"String"},"mark":{"define":"mark","label":"标　志：","name":"mark","relation":"mark","type":"String"},"number":{"define":"number","label":"件　数：","name":"number","relation":"number","type":"String"},"pack":{"define":"pack","label":"包　装：","name":"pack","relation":"pack","type":"String"},"plan_id":{"define":"plan_id","label":"预报计划编号：","name":"plan_id","relation":"plan_id","type":"String"},"total_weight":{"define":"total_weight","label":"重　量：","name":"total_weight","relation":"total_weight","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","limit":20,"xid":"cargolist"});
 new __Data__(this,{"autoLoad":false,"autoNew":false,"confirmDelete":true,"confirmRefresh":true,"defCols":{"has_container_num":{"define":"has_container_num","label":"已配箱数：","name":"has_container_num","relation":"has_container_num","type":"String"},"id":{"define":"id","label":"指令编号：","name":"id","relation":"id","type":"String"},"loadingtype_zh":{"define":"loadingtype_zh","label":"装箱方式：","name":"loadingtype_zh","relation":"loadingtype_zh","type":"String"},"location_name":{"define":"location_name","label":"作业场地：","name":"location_name","relation":"location_name","type":"String"},"ordertime":{"define":"ordertime","label":"指令日期：","name":"ordertime","relation":"ordertime","rules":{"readonly":"true"},"type":"String"},"status_zh":{"define":"status_zh","label":"作业状态：","name":"status_zh","relation":"status_zh","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"insDetailDataCustomRefresh"},"idColumn":"id","initData":"[]","limit":20,"xid":"insDetailData"});
}}); 
return __result;});
