window.__justep.__ResourceEngine.loadCss([{url: '/system/components/comp.min.css', include: '$model/system/components/justep/row/css/row,$model/system/components/justep/attachment/css/attachment,$model/system/components/justep/barcode/css/barcodeImage,$model/system/components/bootstrap/form/css/form,$model/system/components/justep/panel/css/panel,$model/system/components/bootstrap/accordion/css/accordion,$model/system/components/justep/common/css/scrollable,$model/system/components/bootstrap/pager/css/pager,$model/system/components/justep/scrollView/css/scrollView,$model/system/components/justep/input/css/datePickerPC,$model/system/components/bootstrap/navs/css/navs,$model/system/components/justep/contents/css/contents,$model/system/components/justep/popMenu/css/popMenu,$model/system/components/justep/lib/css/icons,$model/system/components/justep/titleBar/css/titleBar,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/justep/dialog/css/dialog,$model/system/components/justep/messageDialog/css/messageDialog,$model/system/components/bootstrap/navbar/css/navbar,$model/system/components/justep/toolBar/css/toolBar,$model/system/components/justep/popOver/css/popOver,$model/system/components/justep/loadingBar/loadingBar,$model/system/components/justep/input/css/datePicker,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/bootstrap/dialog/css/dialog,$model/system/components/justep/wing/css/wing,$model/system/components/bootstrap/scrollSpy/css/scrollSpy,$model/system/components/justep/menu/css/menu,$model/system/components/justep/numberSelect/css/numberList,$model/system/components/justep/list/css/list,$model/system/components/bootstrap/carousel/css/carousel,$model/system/components/bootstrap/dropdown/css/dropdown,$model/system/components/justep/common/css/forms,$model/system/components/justep/bar/css/bar,$model/system/components/bootstrap/tabs/css/tabs,$model/system/components/bootstrap/pagination/css/pagination'},{url: '/system/components/bootstrap.min.css', include: '$model/system/components/bootstrap/lib/css/bootstrap,$model/system/components/bootstrap/lib/css/bootstrap-theme'}]);window.__justep.__ResourceEngine.loadJs(['/system/components/comp.min.js','/system/common.min.js','/system/core.min.js']);define(function(require){
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/labelEdit/labelEdit');
require('$model/UI2/system/components/justep/row/row');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/button/buttonGroup');
require('$model/UI2/system/components/justep/list/list');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/input/input');
require('$model/UI2/system/components/justep/output/output');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/costacoSecond/MtoM/beginworking_firststep'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='__baseID__';
	this.__cid='cVNJR7n';
	this._flag_='ed39c40f5c5b251726bcdf13d10f8f72';
	this.callParent(contextUrl);
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"classes":{"define":"classes","label":"危险等级","name":"classes","relation":"classes","type":"String"},"ctnno":{"define":"ctnno","label":"箱号","name":"ctnno","relation":"ctnno","type":"String"},"ctnsize":{"define":"ctnsize","label":"箱尺寸","name":"ctnsize","relation":"ctnsize","type":"String"},"ctntype":{"define":"ctntype","label":"箱型","name":"ctntype","relation":"ctntype","type":"String"},"flflag":{"define":"flflag","label":"集装箱状态","name":"flflag","relation":"flflag","type":"String"},"id":{"define":"id","label":"ID","name":"id","relation":"id","type":"String"},"numbersofpackages":{"define":"numbersofpackages","label":"件数","name":"numbersofpackages","relation":"numbersofpackages","type":"String"},"operator":{"define":"operator","label":"操作理货员id","name":"operator","relation":"operator","type":"String"},"plan_id":{"define":"plan_id","label":"预报计划ID","name":"plan_id","relation":"plan_id","type":"String"},"sealno":{"define":"sealno","label":"铅封号","name":"sealno","relation":"sealno","type":"String"},"status":{"define":"status","label":"状态","name":"status","relation":"status","type":"String"},"undgno":{"define":"undgno","label":"联合国编号","name":"undgno","relation":"undgno","type":"String"},"volume":{"define":"volume","label":"体积","name":"volume","relation":"volume","type":"String"},"weight":{"define":"weight","label":"重量","name":"weight","relation":"weight","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"ctndetailsDataCustomRefresh"},"idColumn":"id","limit":20,"xid":"ctndetailsData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"cargo_picture":{"define":"cargo_picture","name":"cargo_picture","relation":"cargo_picture","type":"String"},"damage_img":{"define":"damage_img","name":"damage_img","relation":"damage_img","type":"String"},"damage_remark":{"define":"damage_remark","name":"damage_remark","relation":"damage_remark","type":"String"},"door_picture":{"define":"door_picture","name":"door_picture","relation":"door_picture","type":"String"},"seal_picture":{"define":"seal_picture","name":"seal_picture","relation":"seal_picture","type":"String"},"true_sealno":{"define":"true_sealno","name":"true_sealno","relation":"true_sealno","type":"String"}},"directDelete":false,"events":{},"idColumn":"true_sealno","initData":"[{}]","limit":20,"xid":"workinfo"});
}}); 
return __result;});
