window.__justep.__ResourceEngine.loadCss([{url: '/system/components/comp.min.css', include: '$model/system/components/justep/row/css/row,$model/system/components/justep/attachment/css/attachment,$model/system/components/justep/barcode/css/barcodeImage,$model/system/components/bootstrap/form/css/form,$model/system/components/justep/panel/css/panel,$model/system/components/bootstrap/accordion/css/accordion,$model/system/components/justep/common/css/scrollable,$model/system/components/bootstrap/pager/css/pager,$model/system/components/justep/scrollView/css/scrollView,$model/system/components/justep/input/css/datePickerPC,$model/system/components/bootstrap/navs/css/navs,$model/system/components/justep/contents/css/contents,$model/system/components/justep/popMenu/css/popMenu,$model/system/components/justep/lib/css/icons,$model/system/components/justep/titleBar/css/titleBar,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/justep/dialog/css/dialog,$model/system/components/justep/messageDialog/css/messageDialog,$model/system/components/bootstrap/navbar/css/navbar,$model/system/components/justep/toolBar/css/toolBar,$model/system/components/justep/popOver/css/popOver,$model/system/components/justep/loadingBar/loadingBar,$model/system/components/justep/input/css/datePicker,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/bootstrap/dialog/css/dialog,$model/system/components/justep/wing/css/wing,$model/system/components/bootstrap/scrollSpy/css/scrollSpy,$model/system/components/justep/menu/css/menu,$model/system/components/justep/numberSelect/css/numberList,$model/system/components/justep/list/css/list,$model/system/components/bootstrap/carousel/css/carousel,$model/system/components/bootstrap/dropdown/css/dropdown,$model/system/components/justep/common/css/forms,$model/system/components/justep/bar/css/bar,$model/system/components/bootstrap/tabs/css/tabs,$model/system/components/bootstrap/pagination/css/pagination'},{url: '/system/components/bootstrap.min.css', include: '$model/system/components/bootstrap/lib/css/bootstrap,$model/system/components/bootstrap/lib/css/bootstrap-theme'}]);window.__justep.__ResourceEngine.loadJs(['/system/components/comp.min.js','/system/common.min.js','/system/core.min.js']);define(function(require){
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/labelEdit/labelEdit');
require('$model/UI2/system/components/justep/row/row');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/list/list');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/contents/contents');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/scrollView/scrollView');
require('$model/UI2/system/components/justep/contents/content');
require('$model/UI2/system/components/justep/messageDialog/messageDialog');
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/output/output');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/costacoSecond/MtoM/working'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='__baseID__';
	this.__cid='cArqM3e';
	this._flag_='983a22ff635bc7bbba9a506e3e1c8899';
	this.callParent(contextUrl);
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"business":{"define":"business","label":"业务系统","name":"business","relation":"business","type":"String"},"cargonumber":{"define":"cargonumber","label":"货物数量","name":"cargonumber","relation":"cargonumber","type":"String"},"damageno":{"define":"damageno","label":"残损数字","name":"damageno","relation":"damageno","type":"String"},"levelpictureid":{"define":"levelpictureid","label":"作业明细编号","name":"levelpictureid","relation":"levelpictureid","type":"String"},"operationid":{"define":"operationid","label":"作业表编号","name":"operationid","relation":"operationid","type":"String"},"orderno":{"define":"orderno","label":"单号","name":"orderno","relation":"orderno","type":"String"},"picture":{"define":"picture","label":"每关照片","name":"picture","relation":"picture","type":"String"},"sling":{"define":"sling","label":"关数","name":"sling","relation":"sling","type":"String"}},"directDelete":false,"events":{},"idColumn":"levelpictureid","limit":20,"xid":"sling"});
 new __Data__(this,{"autoLoad":false,"autoNew":true,"confirmDelete":false,"confirmRefresh":false,"defCols":{"cargoweight":{"define":"cargoweight","label":"货物重量：","name":"cargoweight","relation":"cargoweight","type":"String"},"containermaster":{"define":"containermaster","label":"箱主代码：","name":"containermaster","relation":"containermaster","type":"String"},"containerno":{"define":"containerno","label":"集装箱号：","name":"containerno","relation":"containerno","type":"String"},"ctnno":{"define":"ctnno","label":"箱　　号：","name":"ctnno","relation":"ctnno","type":"String"},"ctnsize":{"define":"ctnsize","label":"尺寸","name":"ctnsize","relation":"ctnsize","type":"String"},"ctntype":{"define":"ctntype","label":"箱　　型：","name":"ctntype","relation":"ctntype","type":"String"},"guan":{"define":"guan","label":"关数：","name":"guan","relation":"guan","rules":{"integer":true},"type":"Integer"},"id":{"define":"id","label":"箱ID","name":"id","relation":"id","type":"String"},"is_begin":{"define":"is_begin","label":"是否开始作业","name":"is_begin","relation":"is_begin","type":"String"},"is_must":{"define":"is_must","label":"是否必须做","name":"is_must","relation":"is_must","type":"String"},"kximg":{"define":"kximg","label":"是否拍摄空箱：","name":"kximg","relation":"kximg","rules":{"integer":true},"type":"Integer"},"numbersofpackages":{"define":"numbersofpackages","label":"件　　数：","name":"numbersofpackages","relation":"numbersofpackages","type":"String"},"plan_id":{"define":"plan_id","label":"预报id","name":"plan_id","relation":"plan_id","type":"String"},"qbjobcontainerid":{"define":"qbjobcontainerid","label":"qbjobcontainerid","name":"qbjobcontainerid","relation":"qbjobcontainerid","type":"String"},"qbjobinstructionid":{"define":"qbjobinstructionid","label":"指令编号：","name":"qbjobinstructionid","relation":"qbjobinstructionid","type":"String"},"qbzx_operationid":{"define":"qbzx_operationid","label":"作业表id：","name":"qbzx_operationid","relation":"qbzx_operationid","type":"String"},"sealno":{"define":"sealno","label":"铅封号：","name":"sealno","relation":"sealno","type":"String"},"status":{"define":"status","label":"状　　态：","name":"status","relation":"status","rules":{"integer":true},"type":"Integer"},"status_zh":{"define":"status_zh","label":"中文状态","name":"status_zh","relation":"status_zh","type":"String"},"unpackagingplace":{"define":"unpackagingplace","label":"拆箱地点：","name":"unpackagingplace","relation":"unpackagingplace","type":"String"},"zhstatus":{"define":"zhstatus","label":"作业状态：","name":"zhstatus","relation":"zhstatus","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"doDataCustomRefresh"},"idColumn":"qbjobcontainerid","limit":20,"xid":"doData"});
 new __Data__(this,{"autoLoad":false,"autoNew":true,"confirmDelete":false,"confirmRefresh":false,"defCols":{"cargoweight":{"define":"cargoweight","label":"货物重量：","name":"cargoweight","relation":"cargoweight","type":"String"},"containermaster":{"define":"containermaster","label":"箱主代码：","name":"containermaster","relation":"containermaster","type":"String"},"containerno":{"define":"containerno","label":"集装箱号：","name":"containerno","relation":"containerno","type":"String"},"ctnno":{"define":"ctnno","label":"箱　　号：","name":"ctnno","relation":"ctnno","type":"String"},"ctnsize":{"define":"ctnsize","label":"尺寸","name":"ctnsize","relation":"ctnsize","type":"String"},"ctntype":{"define":"ctntype","label":"箱　　型：","name":"ctntype","relation":"ctntype","type":"String"},"guan":{"define":"guan","label":"关数：","name":"guan","relation":"guan","rules":{"integer":true},"type":"Integer"},"id":{"define":"id","label":"箱ID","name":"id","relation":"id","type":"String"},"is_begin":{"define":"is_begin","label":"是否开始作业","name":"is_begin","relation":"is_begin","type":"String"},"is_must":{"define":"is_must","label":"是否必须做","name":"is_must","relation":"is_must","type":"String"},"kximg":{"define":"kximg","label":"是否拍摄空箱：","name":"kximg","relation":"kximg","rules":{"integer":true},"type":"Integer"},"numbersofpackages":{"define":"numbersofpackages","label":"件　　数：","name":"numbersofpackages","relation":"numbersofpackages","type":"String"},"operation_id":{"define":"operation_id","name":"operation_id","relation":"operation_id","type":"String"},"plan_id":{"define":"plan_id","label":"预报id","name":"plan_id","relation":"plan_id","type":"String"},"qbjobcontainerid":{"define":"qbjobcontainerid","label":"qbjobcontainerid","name":"qbjobcontainerid","relation":"qbjobcontainerid","type":"String"},"qbjobinstructionid":{"define":"qbjobinstructionid","label":"指令编号：","name":"qbjobinstructionid","relation":"qbjobinstructionid","type":"String"},"qbzx_operationid":{"define":"qbzx_operationid","label":"作业表id：","name":"qbzx_operationid","relation":"qbzx_operationid","type":"String"},"sealno":{"define":"sealno","label":"铅封号：","name":"sealno","relation":"sealno","type":"String"},"status":{"define":"status","label":"状　　态：","name":"status","relation":"status","rules":{"integer":true},"type":"Integer"},"status_zh":{"define":"status_zh","label":"中文状态","name":"status_zh","relation":"status_zh","type":"String"},"unpackagingplace":{"define":"unpackagingplace","label":"拆箱地点：","name":"unpackagingplace","relation":"unpackagingplace","type":"String"},"zhstatus":{"define":"zhstatus","label":"作业状态：","name":"zhstatus","relation":"zhstatus","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"DoingDataCustomRefresh"},"idColumn":"qbjobcontainerid","limit":20,"xid":"DoingData"});
 new __Data__(this,{"autoLoad":false,"autoNew":true,"confirmDelete":false,"confirmRefresh":false,"defCols":{"cargoweight":{"define":"cargoweight","label":"货物重量：","name":"cargoweight","relation":"cargoweight","type":"String"},"containermaster":{"define":"containermaster","label":"箱主代码：","name":"containermaster","relation":"containermaster","type":"String"},"containerno":{"define":"containerno","label":"集装箱号：","name":"containerno","relation":"containerno","type":"String"},"ctnno":{"define":"ctnno","label":"箱　　号：","name":"ctnno","relation":"ctnno","type":"String"},"ctnsize":{"define":"ctnsize","label":"尺寸","name":"ctnsize","relation":"ctnsize","type":"String"},"ctntype":{"define":"ctntype","label":"箱　　型：","name":"ctntype","relation":"ctntype","type":"String"},"guan":{"define":"guan","label":"关数：","name":"guan","relation":"guan","rules":{"integer":true},"type":"Integer"},"id":{"define":"id","label":"箱ID","name":"id","relation":"id","type":"String"},"is_begin":{"define":"is_begin","label":"是否开始作业","name":"is_begin","relation":"is_begin","type":"String"},"is_must":{"define":"is_must","label":"是否必须做","name":"is_must","relation":"is_must","type":"String"},"kximg":{"define":"kximg","label":"是否拍摄空箱：","name":"kximg","relation":"kximg","rules":{"integer":true},"type":"Integer"},"numbersofpackages":{"define":"numbersofpackages","label":"件　　数：","name":"numbersofpackages","relation":"numbersofpackages","type":"String"},"plan_id":{"define":"plan_id","label":"预报id","name":"plan_id","relation":"plan_id","type":"String"},"qbjobcontainerid":{"define":"qbjobcontainerid","label":"qbjobcontainerid","name":"qbjobcontainerid","relation":"qbjobcontainerid","type":"String"},"qbjobinstructionid":{"define":"qbjobinstructionid","label":"指令编号：","name":"qbjobinstructionid","relation":"qbjobinstructionid","type":"String"},"qbzx_operationid":{"define":"qbzx_operationid","label":"作业表id：","name":"qbzx_operationid","relation":"qbzx_operationid","type":"String"},"sealno":{"define":"sealno","label":"铅封号：","name":"sealno","relation":"sealno","type":"String"},"status":{"define":"status","label":"状　　态：","name":"status","relation":"status","rules":{"integer":true},"type":"Integer"},"status_zh":{"define":"status_zh","label":"中文状态","name":"status_zh","relation":"status_zh","type":"String"},"unpackagingplace":{"define":"unpackagingplace","label":"拆箱地点：","name":"unpackagingplace","relation":"unpackagingplace","type":"String"},"zhstatus":{"define":"zhstatus","label":"作业状态：","name":"zhstatus","relation":"zhstatus","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"doneDataCustomRefresh"},"idColumn":"qbjobcontainerid","limit":20,"xid":"doneData"});
}}); 
return __result;});
