window.__justep.__ResourceEngine.loadCss([{url: '/system/components/comp.min.css', include: '$model/system/components/justep/row/css/row,$model/system/components/justep/attachment/css/attachment,$model/system/components/justep/barcode/css/barcodeImage,$model/system/components/bootstrap/form/css/form,$model/system/components/justep/panel/css/panel,$model/system/components/bootstrap/accordion/css/accordion,$model/system/components/justep/common/css/scrollable,$model/system/components/bootstrap/pager/css/pager,$model/system/components/justep/scrollView/css/scrollView,$model/system/components/justep/input/css/datePickerPC,$model/system/components/bootstrap/navs/css/navs,$model/system/components/justep/contents/css/contents,$model/system/components/justep/popMenu/css/popMenu,$model/system/components/justep/lib/css/icons,$model/system/components/justep/titleBar/css/titleBar,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/justep/dialog/css/dialog,$model/system/components/justep/messageDialog/css/messageDialog,$model/system/components/bootstrap/navbar/css/navbar,$model/system/components/justep/toolBar/css/toolBar,$model/system/components/justep/popOver/css/popOver,$model/system/components/justep/loadingBar/loadingBar,$model/system/components/justep/input/css/datePicker,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/bootstrap/dialog/css/dialog,$model/system/components/justep/wing/css/wing,$model/system/components/bootstrap/scrollSpy/css/scrollSpy,$model/system/components/justep/menu/css/menu,$model/system/components/justep/numberSelect/css/numberList,$model/system/components/justep/list/css/list,$model/system/components/bootstrap/carousel/css/carousel,$model/system/components/bootstrap/dropdown/css/dropdown,$model/system/components/justep/common/css/forms,$model/system/components/justep/bar/css/bar,$model/system/components/bootstrap/tabs/css/tabs,$model/system/components/bootstrap/pagination/css/pagination'},{url: '/system/components/bootstrap.min.css', include: '$model/system/components/bootstrap/lib/css/bootstrap,$model/system/components/bootstrap/lib/css/bootstrap-theme'}]);window.__justep.__ResourceEngine.loadJs(['/system/components/comp.min.js','/system/common.min.js','/system/core.min.js']);define(function(require){
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/labelEdit/labelEdit');
require('$model/UI2/system/components/justep/row/row');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/list/list');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/controlGroup/controlGroup');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/contents/contents');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/contents/content');
require('$model/UI2/system/components/justep/messageDialog/messageDialog');
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/output/output');
require('$model/UI2/system/components/justep/input/input');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/costacoSecond/QBZX/boxsDetails'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='__baseID__';
	this.__cid='cAbErE3';
	this._flag_='cb82622f2e6768db91714a795d4c5fd4';
	this.callParent(contextUrl);
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"ctn_master":{"define":"ctn_master","label":"箱　主：","name":"ctn_master","relation":"ctn_master","type":"String"},"ctn_size":{"define":"ctn_size","label":"箱型尺寸：","name":"ctn_size","relation":"ctn_size","rules":{"integer":true},"type":"Integer"},"ctnno":{"define":"ctnno","label":"箱　号：","name":"ctnno","relation":"ctnno","rules":{"integer":true},"type":"Integer"},"id":{"define":"id","label":"箱id","name":"id","relation":"id","type":"String"},"instruction_id":{"define":"instruction_id","label":"指令id","name":"instruction_id","relation":"instruction_id","type":"String"},"operator_id":{"define":"operator_id","label":"操作人id","name":"operator_id","relation":"operator_id","type":"String"},"status":{"define":"status","label":"状　态：","name":"status","relation":"status","type":"String"},"status_zh":{"define":"status_zh","label":"状　态：","name":"status_zh","relation":"status_zh","type":"String"},"user_name":{"define":"user_name","label":"操作人：","name":"user_name","relation":"user_name","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","initData":"[{\"sealpicture\":\"\"}]","limit":20,"xid":"boxdetails"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"billno":{"define":"billno","label":"提单号","name":"billno","relation":"billno","type":"String"},"cargo_number":{"define":"cargo_number","label":"货物件数","name":"cargo_number","relation":"cargo_number","type":"String"},"damage_num":{"define":"damage_num","label":"残损件数","name":"damage_num","relation":"damage_num","type":"String"},"id":{"define":"id","name":"id","relation":"id","type":"String"},"level_num":{"define":"level_num","label":"关号","name":"level_num","relation":"level_num","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"slingdetailCustomRefresh"},"idColumn":"level_num","initData":"[{}]","limit":20,"xid":"slingdetail"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"begin_time":{"define":"begin_time","label":"起始作业时间","name":"begin_time","relation":"begin_time","type":"String"},"cargo_weight":{"define":"cargo_weight","label":"货物重量","name":"cargo_weight","relation":"cargo_weight","type":"String"},"ctn_id":{"define":"ctn_id","label":"箱id","name":"ctn_id","relation":"ctn_id","type":"String"},"empty_picture":{"define":"empty_picture","label":"空箱照片","name":"empty_picture","relation":"empty_picture","type":"String"},"empty_weight":{"define":"empty_weight","label":"空箱重量","name":"empty_weight","relation":"empty_weight","type":"String"},"id":{"define":"id","label":"作业id","name":"id","relation":"id","type":"String"},"operator_id":{"define":"operator_id","label":"操作理货员ID","name":"operator_id","relation":"operator_id","type":"String"},"seal_picture":{"define":"seal_picture","label":"铅封照片","name":"seal_picture","relation":"seal_picture","type":"String"},"seal_picture_a":{"define":"seal_picture_a","name":"seal_picture_a","relation":"seal_picture_a","type":"String"},"sealno":{"define":"sealno","label":"铅封号","name":"sealno","relation":"sealno","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","limit":20,"xid":"operationDetails"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"sealnopic":{"define":"sealnopic","label":"铅封照片","name":"sealnopic","relation":"sealnopic","type":"String"}},"directDelete":false,"events":{},"idColumn":"sealnopic","limit":20,"xid":"sealnoPIC"});
}}); 
return __result;});
